### ISSUE TITLE
Cannot add vertical control points in editing mode

### ISSUE THREAD

**Issue by BenBergman** [prisonerjohn/ofxWarp#1]
Using the example application and the master branch of oF I am unable to increase the number of vertical control points of a bilinear or perspective-bilinear warp by pressing F4. The existing warps in the demo with extra control can have their points removed with F3 without issue.

I did notice that pressing F4 caused some points to shift, so something is happening.

Unfortunately I don't have time to try to fix this and make a PR right now but figured I should report the issue.

Thanks for the great plugin!

**Comment by johanjohan** [comment]
@prisonerjohn: I have the same issue as described above. any hints?

**Comment by prisonerjohn** [comment]
I'll look into it this week. Don't remember having issues with this so hopefully it's just an easy fix.

Sorry for delay :/

**Comment by johanjohan** [comment]
thx a lot. this is a great plugin and i wish to use it.

**Comment by prisonerjohn** [comment]
Looks like there's a conflict in the key code values when using the function keys... I've just posted issue [#5948](https://github.com/openframeworks/openFrameworks/issues/5948) on the OF repo, and will see if there's a workaround.

**Comment by prisonerjohn** [comment]
`master` should work properly now. However I'll keep this issue open as the fix is just a hack until I can figure out what's happening on the OF side of things.

**Comment by johanjohan** [comment]
@prisonerjohn: hey Elie, this is phantastic and a quick response. big hug, i love it. it works.

**Comment by prisonerjohn** [comment]
Fixed in f997de1adab86dc21e1f975f8f36e00ec0656953
